name: 'trivy-cve-scan'
description: 'executes trivy CVE scan on selected container url'
inputs:
  container-url:
    description: 'container url to scan'
    required: true
  cve-level:
    description: 'CVE levels to scan, try CRITICAL,HIGH,MEDIUM'
    required: true
    default: 'CRITICAL,HIGH'
  exit-code:
    description: 'if set to 1 will return error on detected CVE'
    required: true
    default: '1'
  dockerio-user:
    description: 'username for docker.io, required to login for pull operation'
    required: true
  dockerio-pass:
    description: 'password for docker.io, required to login for pull operation'
    required: true

runs:
  using: "composite"
  steps:
    - name: execute trivy scan on external container
      run: |
        docker login -u ${{ inputs.dockerio-user }} -p ${{ inputs.dockerio-pass }} && \
        docker run --rm -e http_proxy -e https_proxy -v/var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest i --timeout 15m --security-checks vuln,config --exit-code ${{ inputs.exit-code }} --ignore-unfixed --severity ${{ inputs.cve-level }} ${{ inputs.container-url }} && \
        docker logout
      shell: bash
