---
# automates devops zephyr build env 
#
#####################################################################################################
- hosts: testheads remotehw
#  roles:
#  - intel-jf
#  environment: "{{ vars_env_proxy }}"
  tasks:
    - name: 'remove broken cmake kitware ppa'
      apt_repository:
        repo: deb https://apt.kitware.com/ubuntu/ bionic main
        state: absent
      when: ansible_distribution_release == "bionic"

    - name: 'apt update & install zephyr dependencies'
      apt:
        name: "{{packages}}"
        state: present
        update_cache: yes
      vars:
        packages:
          - git
#          - cmake <-- bionic/stable cmake isn't recent enough for zephyr
          - ninja-build
          - gperf
          - ccache
          - dfu-util
          - device-tree-compiler
          - wget
          - python3-pip
          - python3-setuptools
          - python3-tk
          - python3-wheel
          - xz-utils
          - file
          - make
          - gcc
          - gcc-multilib
          - lcov
          - libsdl2-dev
          - java-common
          - default-jre
          - srecord
          - minicom
          - picocom
          - screen

    - name: 'remove bionic/stable cmake (3.10.x). zephyr requires 3.13.1+'
      apt:
        name: cmake
        state: absent
      when: ansible_distribution_release == "bionic"

# install cmake from ppa
    - name: 'get cmake ppa apt key'
      apt_key:
        url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        state: present
    - name: 'add cmake kitware ppa (bionic)'
      apt_repository:
        repo: deb https://apt.kitware.com/ubuntu/ bionic main
        state: present
      when: ansible_distribution_release == "bionic"
    - name: 'apt update & install cmake from ppa'
      apt:
        name: cmake
        state: present
        update_cache: yes

