properties properties: [[$class: 'GitLabConnectionProperty', gitLabConnection: 'gitlab']]

node() {
    gitlabCommitStatus { sh 'echo "debug"' }

    withEnv([   "ZEPHYR_BASE=$WORKSPACE",
                "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.10.1",
                "ZEPHYR_TOOLCHAIN_VARIANT=zephyr",
                "PYTHONIOENCODING=UTF-8",
                "LC_CTYPE=en_US.UTF-8",
                "http_proxy=http://proxy-chain.intel.com:911",
                "https_proxy=http://proxy-chain.intel.com:911",
                "HTTP_PROXY=http://proxy-chain.intel.com:911",
                "HTTPS_PROXY=http://proxy-chain.intel.com:911"]) {
        stage('checkout') {
            deleteDir()
            git branch: 'v1.14-branch-intel',
	            url: 'ssh://git@gitlab.devtools.intel.com:29418/cvondra/zephyr-test.git'        
	    sh "cd $ZEPHYR_BASE;"
	    //temp workaround, might be SDK bug
            sh "cd cmake/toolchain/zephyr; ln -fs 0.10.0 0.10.1; ln -fs 0.10.0 0.10.2; cd -"
            sh "west init"
        }

	stage('sanity-posix') {
		gitlabCommitStatus(name: 'sanity-posix') {
			sh "scripts/sanitycheck -p native_posix"
		}
	}

	stage('sanity-posix64') {
		gitlabCommitStatus(name: 'sanity-posix64') {
			sh "scripts/sanitycheck -p native_posix64"
		}
	}
	
	stage('build-hello_world') {
		gitlabCommitStatus(name: 'build-hello_world') {
			sh "cd $ZEPHYR_BASE/samples/hello_world; mkdir -p build; cd build; cmake -DBOARD=native_posix ..; make;"
		}	 
	}
    }
}
