name: 'trivy-cve-scan'
description: 'aquasecurity/trivy CVE scan with docker.io login- required when inside Intel intranet to bypass docker.io rate limiting'
inputs:
  container-url:
    description: 'container url to scan'
    required: true
  cve-level:
    description: 'CVE levels to scan, try CRITICAL,HIGH,MEDIUM'
    required: true
    default: 'CRITICAL,HIGH'
  exit-code:
    description: 'if set to 1 will return error on detected CVE'
    required: true
    default: '1'
  dockerio-user:
    description: 'legacy parameter, unused'
    required: false
  dockerio-pass:
    description: 'legacy parameter, unused'
    required: false

runs:
  using: "composite"
  steps:
    - name: run trivy CVE scan
      run: |
        docker run --rm -ehttp_proxy -ehttps_proxy -eno_proxy \
          -v/var/run/docker.sock:/var/run/docker.sock \
          amr-registry.caas.intel.com/zephyrproject/ghcr.io/aquasecurity/trivy:latest i --timeout 15m --security-checks vuln,config \
            --exit-code ${{ inputs.exit-code }} --ignore-unfixed \
            --severity ${{ inputs.cve-level }} ${{ inputs.container-url }}
      shell: bash
