---
# setup swarm master + nodes
# also used to recyle/reset service
#####################################
- hosts: master
  tasks:
  - name: 'stop docker swarm'
    shell: |
      docker service rm zephyr-swarm-production
      sleep 10
    ignore_errors: yes

- hosts: agents
  tasks:
  - name: 'purge docker images, volumes & /build mount points'
    shell: |
      docker system prune -f
      docker volume prune -f
      rm -rf /dev/shm/*
    ignore_errors: yes

#- hosts: agents
#  tasks:
#  - name: 'create /build mount directory'
#    shell: |
#      mkdir -m 777 /dev/shm/stg
#      mkdir -m 777 /dev/shm/prod

#- hosts: master
#  tasks:
#  - name: 'create swarm service'
#    shell: |
#      docker service create --mode global --network host --mount type=bind,src=/dev/shm,dst=/build --mount type=bind,src=/etc/profile.d/proxy.sh,dst=/proxy.sh --name zephyr-swarm-production amr-registry.caas.intel.com/zephyrproject/zephyrci_node:production /node_status.sh
#      docker node update --availability drain {{ ansible_hostname }}
