---
# top-level playbook for fresno.jf.intel.com
- hosts: fresno
  roles:
  - intel-jf
  environment: "{{ vars_env_proxy }}"
- hosts: all
  tasks:
# setup proxy in system environment
  - name: 'set http_proxy in /etc/environment'
    lineinfile:
      path: /etc/environment
      regexp: '^http_proxy='
      line: http_proxy=http://proxy-chain.intel.com:911
  - name: 'set https_proxy in /etc/environment'
    lineinfile:
      path: /etc/environment
      regexp: '^https_proxy='
      line: https_proxy=http://proxy-chain.intel.com:911

# removes python2.7* & install python3-pip
  - name: 'purge python2.7 & install python3-pip'
    raw: 'sudo apt-get -y purge python-minimal; sudo apt-get -y install python3'

# setup ACL for fresno.jf.intel.com

# read-in our acl file
  - name: 'including acl-fresno.yaml'
    include_vars:
      file: acl-fresno.yaml
#           ^ this populates two arrays, access & sudo

# grant access to users in access array
  - name: 'grant machine access to users in access list'
    lineinfile:
      path: /etc/opt/quest/vas/users.allow
      regexp: "{{ item }}"
      line: "{{ item }}"
    loop: "{{ access }}"

# grant sudo to users in sudo array 
  - name: 'grant sudo to users in sudo list'
    user:
      name: "{{ item }}"
      create_home: no
      groups: sudo
      append: yes
    loop: "{{ sudo }}"

