name: labgrid github actions test-bench
on:
  workflow_dispatch:

jobs:
  us-test-matrix:
    runs-on: testhead-hf
    strategy:
      matrix:
        systemNames: [nuc-jf-01,nuc-jf-02,nuc-jf-03]
    steps:
      - uses: actions/checkout@v2
      - name: reserve systems
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/labgrid/reserve@main
        with:
          systemName: ${{ matrix.systemNames }}
          timeoutSecs: 60
      - name: power on systems
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/labgrid/power@main
        with:
          systemName: ${{ matrix.systemNames }}
          powerState: on
      - name: release systems
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/labgrid/release@main
        with:
          systemName: ${{ matrix.systemNames }}

  prc-test-matrix:
    runs-on: testhead-sh
    strategy:
      matrix:
        systemNames: [nuc-sh-01,up2-apl-01]
    steps:
      - uses: actions/checkout@v2
      - name: reserve systems
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/labgrid/reserve@main
        with:
          systemName: ${{ matrix.systemNames }}
          timeoutSecs: 60
      - name: power on systems
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/labgrid/power@main
        with:
          systemName: ${{ matrix.systemNames }}
          powerState: on
      - name: release systems
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/labgrid/release@main
        with:
          systemName: ${{ matrix.systemNames }}
