name: fmos-ci-self-test standard workflow
on:
  workflow_call:
    inputs:
      container:
        required: true
        type: string
      runner:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  fmos-ci-self-test:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    container:
      image: ${{ inputs.container }}
      options: -v/opt/toolchains:/opt/toolchains
    strategy:
      matrix:
        batch: [1, 2, 3]
        batch_total: [ 3 ]
    steps:
      - name: checkout zephyr ci-self-test tag
        uses: actions/checkout@v2
        with:
          path: 'zephyrproject/zephyr'
          repository: 'intel-innersource/os.rtos.zephyr.zephyr.git'
          ref: '1rtos-ci-self-test'
          token: ${{ secrets.token }}
      - name: run 1rtos-ci twister wrapper with batch options
        run: /opt/1rtos/container-api.sh 1rtos-ci $GITHUB_WORKSPACE ${{ matrix.batch }} ${{ matrix.batch_total }}
