name: Run tests on Hardware (Intel)
on:
  push:
    branches:
      - main-intel
      - ci/hwtest/*
  schedule:
    - cron: '15 5 * * *' # once daily @ 05:15 UTC, for now, to avoid conflicts.
  pull_request:
    branches:
      - main-intel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_twister:
    name: '[HW] test ${{ matrix.platform }}'
    defaults:
      run:
        shell: bash
    container:
      image: amr-registry.caas.intel.com/zephyrproject/ci-sdk:v0.26.6
      options: "-v /srv/runner/workspace:/runner/workspace ${{ matrix.container_options }}"
      env:
        TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
        SSH_KEY_FMOS_DEV_SIMICS: ${{ secrets.ISH_SIMICS_NUC_HWTEST_SSH_KEY }}
        SSH_KEY_FMOS_QA_SIMICS: ${{ secrets.ISH_SIMICS_FMOS_QA_SSH }}
        IGK_PRIVATE_KEY: ${{ secrets.IGK_PRIVATE_KEY }}
        HF_PRIVATE_KEY: ${{ secrets.HF_PRIVATE_KEY }}
        LG_CROSSBAR: "ws://admin-fmos.igk.intel.com:80/lg"
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.16.4
    strategy:
      fail-fast: false
      matrix:
        platform_group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
        include:
          - platform_group: 1
            toolchain: 'zephyr'
            platform: "intel_adsp_cavs25"
            scope: acceptance
            hwtype: device
            runner: guest-thor3-5
          - platform_group: 2
            scope: acceptance
            hwtype: simulator
            toolchain: 'xcc'
            platform: 'intel_adsp_ace15_mtpm_sim'
            toolchain_ver: 'RI-2022.10-linux'
            xtensa_core: 'ace10_LX7HiFi4_2022_10'
            variant: 'xt-clang'
            runner: fmos-guest-ubuntu-12c
          - platform_group: 3
            scope: acceptance
            hwtype: simulator
            toolchain: 'xcc'
            platform: 'intel_adsp_ace30_ptl_sim'
            toolchain_ver: 'RI-2022.10-linux'
            xtensa_core: 'ace30_LX7HiFi4_PIF'
            variant: 'xt-clang'
            runner: fmos-guest-ubuntu-12c
          - platform_group: 4
            scope: acceptance
            hwtype: simulator
            toolchain: 'xcc'
            platform: 'intel_adsp_ace20_lnl_sim'
            toolchain_ver: 'RI-2022.10-linux'
            xtensa_core: 'ace10_LX7HiFi4_2022_10'
            variant: 'xt-clang'
            runner: fmos-guest-ubuntu-12c
          - platform_group: 5
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: simulator
            platform: 'nsim_em'
            variant: 'zephyr'
            runner: fmos-guest-ubuntu-24c
          - platform_group: 6
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'mec172xevb_assy6906'
            variant: 'zephyr'
            runner: fmos-testhost-nuc-igk-mec17
            hwmap: "map-igk.yaml"
            container_options: '--privileged --device /dev/ttyUSB0:/dev/ttyUSB0 -v /dev/bus/usb/:/dev/bus/usb -v /dev/serial/by-id:/dev/serial/by-id'
            labgrid_place: "mec17-igk,mec17-igk-dediprog"
            labgrid_timeout: 3
          - platform_group: 7
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'frdm_k64f'
            variant: 'zephyr'
            runner: fmos-testhost-nuc-igk-02
            hwmap: "map-igk.yaml"
            container_options: '--privileged -v /dev/bus/usb/:/dev/bus/usb -v /dev/serial/by-id:/dev/serial/by-id'
            pyocd_board_id: "02400b0150234e45003600045f780029b931000197969900,02400b0150234e45005200045f780021b931000197969900"
            pyocd_timeout: 10
          - platform_group: 8
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'mec15xxevb_assy6853'
            variant: 'zephyr'
            runner: fmos-testhost-nuc-igk-mec15
            hwmap: "map-igk.yaml"
            container_options: '--privileged --device /dev/ttyUSB0:/dev/ttyUSB0 -v /dev/bus/usb/:/dev/bus/usb -v /dev/serial/by-id:/dev/serial/by-id'
            labgrid_place: "mec15-igk,mec15-igk-dediprog"
            labgrid_timeout: 5
          - platform_group: 9
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: "intel_ish_5_8_0_simics"
            variant: 'zephyr'
            runner: fmos-ish-5-8-lnl-igk
            timeout: 120
            container_options: '--cpus="8"'
          - platform_group: 10
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: "intel_ish_5_4_1_simics"
            variant: 'zephyr'
            runner: fmos-ish-5-4-mtl-igk
            timeout: 240
            container_options: '--cpus="8"'
          - platform_group: 11
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: "intel_ish_5_4_1"
            # Use this map until we have the same platform id for Simics and HW boards.
            hwmap: "map-igk.yaml"
            variant: 'zephyr'
            runner: fmos-ish-5-4-tgl-igk
            timeout: 240
            container_options: '--cpus="8"'
          - platform_group: 12
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'npcx9m6f_evb'
            variant: 'zephyr'
            runner: fmos-testhost-nuc-igk-03
            hwmap: "map-igk.yaml"
            container_options: '--privileged -v /dev/bus/usb/:/dev/bus/usb -v /dev/serial/by-id:/dev/serial/by-id'
          - platform_group: 13
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'up_squared'
            variant: 'zephyr'
            timeout: 120
            runner: fmos-up_squared-igk
            hwmap: "map-igk.yaml"
          - platform_group: 14
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: "it8xxx2_evb"
            hwmap: "map-igk.yaml"
            container_options: '--privileged -v /dev/bus/usb/:/dev/bus/usb -v /dev/serial/by-id:/dev/serial/by-id'
            variant: 'zephyr'
            runner: fmos-testhost-nuc-igk-04
            labgrid_place: "ite-board-ci_01,ite-board-dbg_01"
            labgrid_timeout: 10
          - platform_group: 15
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'intel_adsp_ace15_mtpm'
            toolchain_ver: 'RI-2022.10-linux'
            xtensa_core: 'ace10_LX7HiFi4_2022_10'
            variant: 'xt-clang'
            runner: fmos-mtl-igk
            hwmap: "map-igk.yaml"
          - platform_group: 16
            toolchain: 'zephyr'
            scope: acceptance
            hwtype: device
            platform: 'intel_adsp_ace20_lnl'
            toolchain_ver: 'RI-2022.10-linux'
            xtensa_core: 'ace10_LX7HiFi4_2022_10'
            variant: 'xt-clang'
            runner: fmos-guest-ubuntu-12c-igk
            hwmap: "map-igk.yaml"

    runs-on: ${{ matrix.runner }}
    timeout-minutes: ${{ matrix.timeout || 180 }}
    steps:
      - name: Clean Workspace
        run: |
          # set dotglob so rm will remove dot files and dirs - (.west, etc.)
          shopt -s dotglob
          pwd
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Environment Setup
        shell: bash
        run: |
          touch $HOME/.git-credentials
          touch $HOME/.gitconfig
          git config --global user.email "sys_tmbuild@intel.com"
          git config --global user.name "Github Builder CI"
          git config --global credential.helper 'store --file=$HOME/.git-credentials'

          mkdir -p /home/user/.ssh
          echo -e "Host *\n    User zephyr\n    StrictHostKeyChecking no" >> /home/user/.ssh/config
          if [ ! -f "/__w/os.rtos.zephyr.zephyr/.west/config" ]; then
            west init -l . || true
          fi
          west config --global update.narrow true
          #west config --global update.path-cache "/runner/workspace"
          # we need this here because our local manifest does import this repo
          echo -e "https://$TOKEN:$TOKEN@github.com/intel-innersource/drivers.audio.firmware.converged" > $HOME/.git-credentials
          west update  2>&1 1> west.update.log || ( rm -rf ../intel ../modules ../bootloader ../tools && west update )
          for r in `west  list -f {url} | grep intel-innersource | sed 's#https://##'`; do
            echo -e "https://$TOKEN:$TOKEN@$r" >> $HOME/.git-credentials
          done
          # debug
          cat $HOME/.git-credentials
          git config --global --add safe.directory ${PWD}
          west update
          west forall -c 'git reset --hard HEAD'

      - name: Reset platform with pyocd
        if: ${{ matrix.pyocd_board_id }}
        shell: bash
        run: |
            echo "Resetting ${{ matrix.platform }} with pyocd"
            python3 scripts/support/prepare_platform.py --pyocd-board-id "${{ matrix.pyocd_board_id }}" --pyocd-timeout $PYOCD_TIMEOUT
        env:
          PYOCD_TIMEOUT: ${{ matrix.pyocd_timeout || 5 }}

      - name: Reset platform with labgrid
        if: ${{ matrix.labgrid_place }}
        shell: bash
        run: |
          echo "Resetting ${{ matrix.platform }} with labgrid, labgrid-crossbar: $LG_CROSSBAR"
          eval $(ssh-agent -s) && echo "$IGK_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          python3 scripts/support/prepare_platform.py --labgrid-place "${{ matrix.labgrid_place }}" --labgrid-crossbar "$LG_CROSSBAR" --labgrid-timeout $LG_TIMEOUT
        env:
          LG_TIMEOUT: ${{ matrix.labgrid_timeout || 5 }}

      - name: Build RIMAGE
        run: |
          pushd ../modules/audio/sof/tools/rimage
          cmake -B build/
          make  -C build/
          sudo cp build/rimage /usr/local/bin/
          popd
      - name: Execute Tests
        run: |
          export MEC172X_SPI_GEN=/opt/tools/bin/mec172x_spi_gen_lin_x86_64
          export EVERGLADES_SPI_GEN=/opt/tools/bin/everglades_spi_gen_lin64
          export PATH=/opt/tools/bin:$PATH
          # device vs sim
          HW_MAP="map.yaml"
          if [ ${{ matrix.hwmap }} ]; then
            HW_MAP=${{ matrix.hwmap }}
          fi
          if [ ${{ matrix.hwtype }} == 'device' ]; then
            export DEV_TYPE="-x=CONFIG_BOOT_DELAY=500 --device-testing --hardware-map .github/data/${HW_MAP}"
          fi
          # toolchain
          if [ ${{ matrix.toolchain }} == 'xcc' ]; then
            export ZEPHYR_TOOLCHAIN_VARIANT=${{ matrix.variant }}
            export XTENSA_TOOLCHAIN_PATH=/opt/toolchains/xtensa/XtDevTools/install/tools
            export XTENSA_CORE=${{ matrix.xtensa_core }}
            export TOOLCHAIN_VER=${{ matrix.toolchain_ver }}
            export XTENSA_BUILDS_DIR=/opt/toolchains/xtensa/XtDevTools/install/builds
            export TWISTER_QUARANTINE_LIST=.github/data/xcc-twister-quarantine-list.yml
            export XTENSA_SYSTEM=/opt/toolchains/xtensa/XtDevTools/install/tools/${{ matrix.toolchain_ver }}/XtensaTools/config/
          else
            export TWISTER_QUARANTINE_LIST=.github/data/twister-quarantine-list.yml
          fi

          export PATH=$PATH:/opt/tools/bin
          if [ "${{github.event_name}}" = "pull_request" ]; then
            TEST_COV=smoke
          else
            TEST_COV=${{ matrix.scope }}
          fi

          # Ensure local network is not accessed via proxy
          export no_proxy=$no_proxy,192.168.0.0/16

          eval $(ssh-agent -s)
          echo "$SSH_KEY_FMOS_DEV_SIMICS" | tr -d '\r' | ssh-add -
          echo "$SSH_KEY_FMOS_QA_SIMICS" | tr -d '\r' | ssh-add -
          # faceless key used to access platforms located in IGK
          echo "$IGK_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          ./scripts/twister -M -x=USE_CCACHE=0 --inline-logs \
            --force-color -v \
            --quarantine-list $TWISTER_QUARANTINE_LIST \
            --disable-suite-name-check \
            --retry-build-errors \
            --retry-failed 2 \
            --retry-interval 15 \
            --test-config .github/data/test_config.yaml \
            --level $TEST_COV \
            $DEV_TYPE \
            -p ${{ matrix.platform }}

      - name: Archive twister-out directory
        id: tar-twister-out
        if: (success() || failure() || cancelled())
        run: |
         # Give some time to Twister processes to close logs on cancel.
         [ $(ps -ef | grep twister | wc -l) -ge 2 ] && sleep 60s
         [ -d ./twister-out ] && sync ./twister-out && find ./twister-out -type f -name "*.log" | tar -czf subset-${{ matrix.platform_group }}-${{ matrix.platform }}-twister-out.tar.gz -T -
      - name: Upload twister-out.tar.gz archive per subset
        if: (steps.tar-twister-out.outcome == 'success') && (success() || failure() || cancelled())
        uses: actions/upload-artifact@v2
        with:
          name: subset-${{ matrix.platform_group }}-${{ matrix.platform }}-twister-out archive in .tar.gz format
          path: |
            subset-${{ matrix.platform_group }}-${{ matrix.platform }}-twister-out.tar.gz
          retention-days: 5

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Subset ${{ matrix.platform_group }})
          path: |
            twister-out/twister.log
            twister-out/twister.xml
            twister-out/twister.json
          retention-days: 14

  publish-test-results:
    container:
      image: amr-registry.caas.intel.com/zephyrproject/ci-sdk:v0.26.6
      env:
        TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
    env:
      ELASTICSEARCH_KEY: ${{ secrets.ELASTICSEARCH_KEY }}
      ELASTICSEARCH_SERVER: 'https://reports-fmos.hf.intel.com:9200'
      BRANCH_NAME: ${{ github.event_name == 'schedule' && 'master' || 'test_branch' }}
    name: '[HW] Publish Test Results'
    needs: [run_twister]
    runs-on: fmos-guest-ubuntu-12c
    continue-on-error: true
    if: success() || failure()
    steps:
      - name: Get current date
        id: run_date
        run: |
          echo "run_date=$(date --iso-8601=minutes)" >> "$GITHUB_OUTPUT"
          echo "run_date_short=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Clean and Pre Environment
        run: |
          rm -rf artifacts
          pip3 install elasticsearch

      - name: Checkout
        # if: github.event_name == 'schedule' || github.event_name == 'push'
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Upload to ElasticSearch Instance
        if: github.event_name == 'schedule'
        run: |
          echo ${{ steps.run_date.outputs.run_date }}
          python3 ./scripts/ci/upload_test_results_es.py -r ${{ steps.run_date.outputs.run_date }} \
            -i zephyr-tests-main-intel-daily-1 artifacts/**/twister.json

      - name: Upload to ElasticSearch Instance
        if: github.event_name == 'push'
        run: |
          echo ${{ steps.run_date.outputs.run_date }}
          python3 ./scripts/ci/upload_test_results_es.py -r ${{ steps.run_date.outputs.run_date }} \
            -i zephyr-tests-main-intel-1 artifacts/**/twister.json

      - name: Upload to ElasticSearch Instance
        if: github.event_name == 'pull_request'
        # for testing purposes
        run: |
          echo ${{ steps.run_date.outputs.run_date }}
          python3 ./scripts/ci/upload_test_results_es.py -r ${{ steps.run_date.outputs.run_date }} \
            -i zephyr-tests-staging-1 artifacts/**/twister.json

      - name: Upload to Static Report Server - Clean and Pre Environment
        id: srs-prep-data
        run: |
          rm -rf ${{ steps.run_date.outputs.run_date_short }}
          cp -r artifacts ${{ steps.run_date.outputs.run_date_short }}
          cp ./scripts/ci/upload_test_results_sr.py ${{ steps.run_date.outputs.run_date_short }}/

      - name: Upload to Static Report Server - Upload
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/fmos-scp-ssh-pipeline@main
        if: steps.srs-prep-data.outcome == 'success'
        with:
          hostname: 'zep-fmos-static-reporting.igk.intel.com'
          ssh-user: 'zephyr'
          ssh-key: ${{ secrets.IGK_PRIVATE_KEY }}
          ssh-pre: |
            'if [[ ! -d "/media/dskpool/ws-ztest/zephyrproject/daily_report/sumreport/${{ env.BRANCH_NAME }}/" ]]; then \
            mkdir -p /media/dskpool/ws-ztest/zephyrproject/daily_report/sumreport/${{ env.BRANCH_NAME }}/; fi'
          scp-src: '${{ steps.run_date.outputs.run_date_short }}/'
          scp-dst: '/media/dskpool/ws-ztest/zephyrproject/daily_report/sumreport/${{ env.BRANCH_NAME }}/'
          ssh-post: |
            'cd /media/dskpool/ws-ztest/zephyrproject/daily_report/sumreport/${{ env.BRANCH_NAME }}/ && \
            if [ -f "${{ steps.run_date.outputs.run_date_short }}/upload_test_results_sr.py" ]; then \
            cd ${{ steps.run_date.outputs.run_date_short }} && \
            python3 upload_test_results_sr.py --workflow "${{ github.workflow }}" && \
            rm -f upload_test_results_sr.py; fi'
          scp-rollback: true

      - name: Upload to Static Report Server - Clean
        if: steps.srs-prep-data.outcome == 'success'
        run: |
          rm -rf ${{ steps.run_date.outputs.run_date_short }}

      - name: Publish Unit Test Results
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/results-publisher@main
        with:
          files: 'artifacts/**/twister.xml'
          check_name: 'Hardware Test Results'
          comment_mode: off
          compare_to_earlier_commit: false
