# RemoteHW-Deploy 
#   triggered on push to main:src/remotehw/, this workflow uses scp to deploy 
#   remoteHW configuration & scripts to zephyrtest-blue. This method requires
#   the runner user be pre-authenticated. See FMOS-DevOps-KeyRoll workflow.

name: RemoteHW-Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'src/remotehw/**'    
  workflow_dispatch:
        
jobs:
  deploy_zephyrtest-blue:
    defaults:
      run:
        shell: bash  
    runs-on: testhead
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: deploy src/remotehw/opt/* to /opt/remotehw
        run: |
         scp repo/src/remotehw/opt/* zephyrtest-blue.jf.intel.com:/opt/remotehw/
         ssh zephyrtest-blue.jf.intel.com chmod 644 /opt/remotehw/*
         ssh zephyrtest-blue.jf.intel.com chmod 755 /opt/remotehw/*.sh
         ssh zephyrtest-blue.jf.intel.com chmod 755 /opt/remotehw/*.exp
      - name: deploy src/remotehw/profile/remotehw* to /etc/profile.d
        run: |
         scp repo/src/remotehw/profile/remotehw* zephyrtest-blue.jf.intel.com:/etc/profile.d/
         ssh zephyrtest-blue.jf.intel.com chmod 644 /etc/profile.d/remotehw*
         ssh zephyrtest-blue.jf.intel.com chmod 755 /etc/profile.d/remotehw*.sh
